FROM deploy.deepexi.com/console/fastdata-workbench:0.4.1-2


# docker build -t deploy.deepexi.com/console/fastdata-workbench:0.4.1-2 .
# docker  build . -t deploy.deepexi.com/console/fastdata-workbench:0.4.1-2-arm  --platform linux/arm64
