FROM apache/apisix-dashboard:2.13.1-alpine@sha256:b19575b81db31202bcfa99117f93ecaecf6eac48c47dd53a95ce5c3aa69da4ed

# docker buildx build . -t deploy.deepexi.com/dag-dev/apisix-dashboard:2.13.1-arm --platform  linux/arm64
# docker push deploy.deepexi.com/dag-dev/apisix-dashboard:2.13.1-arm